version: 2

updates:

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
    open-pull-requests-limit: 10
    target-branch: main
