languages:
  Ruby: false
  JavaScript: false
  PHP: true
  Python: false
exclude_paths: ["tests"]
plugins:
  markdownlint:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      standard: "phpcs.xml.dist"
